name: AstroGlass
options:
  bundleIdPrefix: com.idreamstudios
  deploymentTarget:
    iOS: "26.0"
  xcodeVersion: "26.0"
  createIntermediateGroups: true
packages:
  GoogleMobileAds:
    url: https://github.com/googleads/swift-package-manager-google-mobile-ads.git
    from: 13.0.0
settings:
  base:
    SWIFT_VERSION: 6.0
    OTHER_LDFLAGS: "-ObjC"
    IPHONEOS_DEPLOYMENT_TARGET: "26.0"
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    TARGETED_DEVICE_FAMILY: "1"
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
configs:
  Debug: debug
  Release: release
schemes:
  AstroGlass:
    build:
      targets:
        AstroGlass: all
    test:
      targets:
        - AstroGlassTests
targets:
  AstroGlass:
    type: application
    platform: iOS
    sources:
      - path: AstroGlass
    resources:
      - path: AstroGlass/Resources
    dependencies:
      - package: GoogleMobileAds
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.idreamstudios.astroglass
        PRODUCT_NAME: AstroGlass
        INFOPLIST_FILE: AstroGlass/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Automatic
        SWIFT_ENABLE_EXPLICIT_MODULES: NO
  AstroGlassTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: AstroGlassTests
    dependencies:
      - target: AstroGlass
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.idreamstudios.astroglass.tests
        PRODUCT_NAME: AstroGlassTests
        PRODUCT_MODULE_NAME: AstroGlassTests
        GENERATE_INFOPLIST_FILE: YES
